ALTER TABLE auth_groups RENAME TO auth_group;
ALTER TABLE auth_groups_permissions RENAME TO auth_group_permissions;
ALTER TABLE auth_messages RENAME TO auth_message;
ALTER TABLE auth_permissions RENAME TO auth_permission;
ALTER TABLE auth_users RENAME TO auth_user;
ALTER TABLE auth_users_groups RENAME TO auth_user_groups;
ALTER TABLE auth_users_user_permissions RENAME TO auth_user_user_permissions;
ALTER TABLE content_types RENAME TO django_content_type;
ALTER TABLE core_sessions RENAME TO django_session;
ALTER TABLE sites RENAME TO django_site;
DROP TABLE packages;
truncate auth_permission;
truncate auth_group_permissions;
truncate auth_user_user_permissions;
truncate django_content_type;
ALTER TABLE django_content_type CHANGE package app_label VARCHAR(100) NOT NULL,
  CHANGE python_module_name model VARCHAR(100) NOT NULL;
ALTER TABLE auth_permission ADD COLUMN content_type_id INTEGER;
ALTER TABLE `auth_permission` DROP COLUMN `package`;
alter table auth_user_groups change rtuser_id user_id int(11) not null default 0;
alter table auth_user_user_permissions change rtuser_id user_id int(11) not null default 0;
alter table index_announcements rename to index_announcement; 
alter table index_closings rename to index_closing;
alter table index_meets rename to index_meet; 
alter table index_pools rename to index_pool;
alter table index_practices rename to index_practice;
alter table index_schedules rename to index_schedule;
alter table index_schedules_practices rename to index_schedule_practices;
alter table mailinglist_mailinglists rename to mailinglist_mailinglist;
alter table mailinglist_mailinglists_swimmers rename to mailinglist_mailinglist_swimmers;
alter table mailinglist_messages rename to mailinglist_message;
alter table registration_payments rename to registration_payment;
alter table registration_paypallogmsgs rename to registration_paypallogmsg;
alter table registration_periods rename to registration_period;
alter table registration_plans rename to registration_plan;
alter table registration_registrations rename to registration_registration;
alter table registration_registrations_payments rename to registration_registrations_payment;
alter table stockphoto_gallerys rename to stockphoto_gallery; 
alter table stockphoto_photos rename to stockphoto_photo;
alter table swimmers_boardmembers rename to swimmers_boardmember;
alter table swimmers_boardpositions rename to swimmers_boardposition;
alter table swimmers_states rename to swimmers_state;
alter table swimmers_swimmers rename to swimmers_swimmer;
/* run syncdb */
